DROP TABLE INTERVENTION_MATIERE CASCADE CONSTRAINTS;
DROP TABLE EFFECTUATION         CASCADE CONSTRAINTS;
DROP TABLE INTERVENTION        CASCADE CONSTRAINTS;
DROP TABLE COMMANDE            CASCADE CONSTRAINTS;
DROP TABLE FABRICATION         CASCADE CONSTRAINTS;
DROP TABLE BAC_INTEL           CASCADE CONSTRAINTS;
DROP TABLE MATIERE_PREMIERE    CASCADE CONSTRAINTS;
DROP TABLE EMPLOYE             CASCADE CONSTRAINTS;
DROP TABLE CLIENT              CASCADE CONSTRAINTS;
CREATE TABLE MATIERE_PREMIERE (
    ID_MP            NUMBER        PRIMARY KEY,
    REFERENCE        VARCHAR2(50)  UNIQUE NOT NULL,
    NOM              VARCHAR2(120) NOT NULL,
    QUANTITE         NUMBER        DEFAULT 0 CHECK (QUANTITE >= 0),
    SEUIL_CRITIQUE   NUMBER        DEFAULT 0 CHECK (SEUIL_CRITIQUE >= 0),
    PRIX             NUMBER(12,3)  DEFAULT 0 CHECK (PRIX >= 0),
    DATE_FABRICATION DATE,
    DATE_ACHAT       DATE,
    NUM_FOUR         NUMBER,
    NOM_FOUR         VARCHAR2(50),
    EMAIL_FOUR       VARCHAR2(150)
);

CREATE TABLE CLIENT (
    ID_CLIENT               NUMBER        PRIMARY KEY,
    NOM                     VARCHAR2(120) NOT NULL,
    MATRICULE               VARCHAR2(50)  UNIQUE,
    EMAIL                   VARCHAR2(120),
    TYPE_CONTRAT            VARCHAR2(50),
    STATUT_PAIEMENT         VARCHAR2(20)
        CHECK (STATUT_PAIEMENT IN ('A_JOUR', 'EN_RETARD', 'SUSPENDU')),
    DATE_EXPIRATION_CONTRAT DATE,
    TAUX_TRI                NUMBER        DEFAULT 0 CHECK (TAUX_TRI BETWEEN 0 AND 100)
);

CREATE TABLE BAC_INTEL (
    ID_BAC             NUMBER        PRIMARY KEY,
    NUM_SERIE          VARCHAR2(60)  UNIQUE NOT NULL,
    MODELE             VARCHAR2(60)  NOT NULL,
    REMPLISSAGE        NUMBER        DEFAULT 0 CHECK (REMPLISSAGE BETWEEN 0 AND 100),
    LOCALISATION_STOCK VARCHAR2(150),
    ID_CLIENT          NUMBER        NULL,
    ID_COMMANDE        NUMBER,
    prix               NUMBER(12,3),
    stock              NUMBER,
    capacite_batterie  NUMBER(8,2),
    caracteristiques   VARCHAR2(500),
    IMAGE_PATH         VARCHAR2(500),
    CONSTRAINT FK_BAC_CLIENT FOREIGN KEY (ID_CLIENT)
        REFERENCES CLIENT(ID_CLIENT)
);

CREATE TABLE FABRICATION (
    ID_MP       NUMBER NOT NULL,
    ID_BAC      NUMBER NOT NULL,
    QTE_UTILISE NUMBER NOT NULL,
    PRIMARY KEY (ID_MP, ID_BAC),
    FOREIGN KEY (ID_MP)
        REFERENCES MATIERE_PREMIERE(ID_MP),
    FOREIGN KEY (ID_BAC)
        REFERENCES BAC_INTEL(ID_BAC)
);

CREATE TABLE EMPLOYE (
    ID_EMP                   NUMBER        PRIMARY KEY,
    MATRICULE                VARCHAR2(30)  UNIQUE NOT NULL,
    CIN                      VARCHAR2(20)  UNIQUE,
    NOM                      VARCHAR2(80)  NOT NULL,
    EMAIL                    VARCHAR2(120) UNIQUE,
    SPECIALITE               VARCHAR2(80),
    DISPONIBILITE            VARCHAR2(20)  DEFAULT 'DISPONIBLE'
        CHECK (DISPONIBILITE IN ('DISPONIBLE', 'INDISPONIBLE', 'EN_INTERVENTION', 'CONGE_NORMALE', 'CONGE_MALADIE', 'EN_CONGE', 'EN_CONGE_MALADIE')),
    PHOTO                    BLOB,
    FACE_TEMPLATE            CLOB,
    FACE_TEMPLATE_UPDATED_AT DATE,
    FACE_ENABLED             NUMBER(1)     DEFAULT 1
);

CREATE TABLE COMMANDE (
    ID_COMMANDE    NUMBER        PRIMARY KEY,
    ID_CLIENT      NUMBER        NOT NULL,
    QTE            NUMBER        NOT NULL CHECK (QTE > 0),
    PRIORITE       VARCHAR2(15)  DEFAULT 'NORMALE'
        CHECK (PRIORITE IN ('FAIBLE', 'NORMALE', 'HAUTE', 'URGENTE')),
    STATUT         VARCHAR2(20)  DEFAULT 'EN_PREPARATION'
        CHECK (STATUT IN ('EN_PREPARATION', 'LIVREE', 'INSTALLEE', 'ANNULEE')),
    DATE_COMMANDE  DATE          DEFAULT SYSDATE,
    DATE_LIVRAISON DATE,
    PRIX_TOTAL     NUMBER(12,3)  DEFAULT 0 CHECK (PRIX_TOTAL >= 0),
    ADRESSE        VARCHAR2(300),
    CONSTRAINT FK_CMD_CLIENT FOREIGN KEY (ID_CLIENT)
        REFERENCES CLIENT(ID_CLIENT)
);

CREATE TABLE COMMANDE_BAC (
    ID_COMMANDE    NUMBER        NOT NULL,
    ID_BAC         NUMBER        NOT NULL,
    QTE            NUMBER        NOT NULL CHECK (QTE > 0),
    PRIX_UNITAIRE  NUMBER(12,3)  DEFAULT 0 NOT NULL CHECK (PRIX_UNITAIRE >= 0),
    CONSTRAINT PK_COMMANDE_BAC PRIMARY KEY (ID_COMMANDE, ID_BAC),
    CONSTRAINT FK_COMMANDE_BAC_CMD FOREIGN KEY (ID_COMMANDE)
        REFERENCES COMMANDE(ID_COMMANDE)
        ON DELETE CASCADE,
    CONSTRAINT FK_COMMANDE_BAC_BAC FOREIGN KEY (ID_BAC)
        REFERENCES BAC_INTEL(ID_BAC)
);

CREATE INDEX IDX_COMMANDE_BAC_BAC ON COMMANDE_BAC(ID_BAC);

CREATE TABLE INTERVENTION (
    ID_INTER   NUMBER        PRIMARY KEY,
    ID_BAC     NUMBER        NOT NULL,
    DATE_INTER DATE          DEFAULT SYSDATE,
    REFERENCE  VARCHAR2(60)  UNIQUE,
    DUREE      NUMBER(6,2)   DEFAULT 0 CHECK (DUREE >= 0),
    COUT       NUMBER(12,3)  DEFAULT 0 CHECK (COUT >= 0),
    MAIN_OEUVRE NUMBER(12,3) DEFAULT 0 CHECK (MAIN_OEUVRE >= 0),
    STATUT     VARCHAR2(20)  DEFAULT 'EN_COURS'
        CHECK (STATUT IN ('EN_COURS', 'EN_ATTENTE', 'TERMINEE', 'ANNULEE')),
    TYPE       VARCHAR2(60),
    PRIORITE   VARCHAR2(15)  DEFAULT 'NORMALE'
        CHECK (PRIORITE IN ('FAIBLE', 'NORMALE', 'HAUTE', 'URGENTE')),
    CONSTRAINT FK_INTER_BAC FOREIGN KEY (ID_BAC)
        REFERENCES BAC_INTEL(ID_BAC)
);

CREATE TABLE EFFECTUATION (
    ID_INTER NUMBER NOT NULL,
    ID_EMP   NUMBER NOT NULL,
    PRIMARY KEY (ID_INTER, ID_EMP),
    FOREIGN KEY (ID_INTER)
        REFERENCES INTERVENTION(ID_INTER),
    FOREIGN KEY (ID_EMP)
        REFERENCES EMPLOYE(ID_EMP)
);

CREATE TABLE INTERVENTION_MATIERE (
    ID_INTER     NUMBER NOT NULL,
    ID_MP        NUMBER NOT NULL,
    QTE_UTILISEE NUMBER NOT NULL CHECK (QTE_UTILISEE > 0),
    PRIMARY KEY (ID_INTER, ID_MP),
    CONSTRAINT FK_IM_INTER FOREIGN KEY (ID_INTER)
        REFERENCES INTERVENTION(ID_INTER),
    CONSTRAINT FK_IM_MP    FOREIGN KEY (ID_MP)
        REFERENCES MATIERE_PREMIERE(ID_MP)
);
