CREATE TABLE COMMANDE_BAC (
    ID_COMMANDE    NUMBER        NOT NULL,
    ID_BAC         NUMBER        NOT NULL,
    QTE            NUMBER        NOT NULL CHECK (QTE > 0),
    PRIX_UNITAIRE  NUMBER(12,3)  DEFAULT 0 NOT NULL CHECK (PRIX_UNITAIRE >= 0),
    CONSTRAINT PK_COMMANDE_BAC PRIMARY KEY (ID_COMMANDE, ID_BAC),
    CONSTRAINT FK_COMMANDE_BAC_CMD FOREIGN KEY (ID_COMMANDE)
        REFERENCES COMMANDE(ID_COMMANDE)
        ON DELETE CASCADE,
    CONSTRAINT FK_COMMANDE_BAC_BAC FOREIGN KEY (ID_BAC)
        REFERENCES BAC_INTEL(ID_BAC)
);

CREATE INDEX IDX_COMMANDE_BAC_BAC ON COMMANDE_BAC(ID_BAC);
