-- Oracle migration: add SALAIRE to EMPLOYE if missing.
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'EMPLOYE'
      AND COLUMN_NAME = 'SALAIRE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE EMPLOYE ADD (SALAIRE NUMBER(12,3) DEFAULT 1200 CHECK (SALAIRE >= 0))';
    END IF;

    EXECUTE IMMEDIATE
        'UPDATE EMPLOYE SET SALAIRE = 1200 WHERE SALAIRE IS NULL';
END;
/

COMMIT;
