-- ============================================================================
-- WasteGuard — Schéma de base de données (Oracle)
-- ----------------------------------------------------------------------------
-- Reflète la base de production réelle (schema WASTEGUARD).
-- Ordre : DROP -> séquences -> tables -> index -> triggers d'auto-incrément.
-- Les données de démonstration sont dans docs/seed.sql (à exécuter ensuite).
--
-- Exécution :
--   sqlplus user/password@base @docs/wasteguard.sql
--   sqlplus user/password@base @docs/seed.sql
-- ============================================================================

-- ---- Nettoyage (ordre enfants -> parents) ----------------------------------
DROP TABLE EFFECTUATION       CASCADE CONSTRAINTS;
DROP TABLE COMMANDE_BAC       CASCADE CONSTRAINTS;
DROP TABLE FABRICATION        CASCADE CONSTRAINTS;
DROP TABLE INTERVENTION       CASCADE CONSTRAINTS;
DROP TABLE COMMANDE           CASCADE CONSTRAINTS;
DROP TABLE BAC_INTEL          CASCADE CONSTRAINTS;
DROP TABLE MATIERE_PREMIERE   CASCADE CONSTRAINTS;
DROP TABLE EMPLOYE            CASCADE CONSTRAINTS;
DROP TABLE CLIENT             CASCADE CONSTRAINTS;
DROP TABLE ADMIN_NOTIFICATION CASCADE CONSTRAINTS;

DROP SEQUENCE CLIENT_SEQ;
DROP SEQUENCE EMPLOYE_SEQ;
DROP SEQUENCE MATIERE_PREMIERE_SEQ;
DROP SEQUENCE BAC_INTEL_SEQ;
DROP SEQUENCE COMMANDE_SEQ;
DROP SEQUENCE SEQ_CMD_REF;
DROP SEQUENCE INTERVENTION_SEQ;
DROP SEQUENCE ADMIN_NOTIFICATION_SEQ;

-- ---- Séquences (START WITH au-dessus des IDs de démonstration) -------------
CREATE SEQUENCE CLIENT_SEQ            START WITH 200  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE EMPLOYE_SEQ           START WITH 300  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MATIERE_PREMIERE_SEQ  START WITH 900  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BAC_INTEL_SEQ         START WITH 500  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMMANDE_SEQ          START WITH 600  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CMD_REF           START WITH 82   INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INTERVENTION_SEQ      START WITH 800  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ADMIN_NOTIFICATION_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;

-- ============================================================================
--  TABLES
-- ============================================================================

CREATE TABLE CLIENT (
    ID_CLIENT               NUMBER,
    NOM                     VARCHAR2(120) NOT NULL,
    MATRICULE               VARCHAR2(50),
    EMAIL                   VARCHAR2(120),
    TYPE_CONTRAT            VARCHAR2(50),
    STATUT_PAIEMENT         VARCHAR2(20),
    DATE_EXPIRATION_CONTRAT DATE,
    TAUX_TRI                NUMBER       DEFAULT 0,
    TELEPHONE               VARCHAR2(30),
    DATE_CREATION_CONTRAT   DATE,
    CONSTRAINT PK_CLIENT           PRIMARY KEY (ID_CLIENT),
    CONSTRAINT UQ_CLIENT_MATRICULE UNIQUE (MATRICULE),
    CONSTRAINT CK_CLIENT_TAUX      CHECK (TAUX_TRI BETWEEN 0 AND 100),
    CONSTRAINT CK_CLIENT_PAIEMENT  CHECK (STATUT_PAIEMENT IN ('A_JOUR', 'EN_RETARD', 'SUSPENDU'))
);

CREATE TABLE EMPLOYE (
    ID_EMP                   NUMBER,
    MATRICULE                VARCHAR2(30)  NOT NULL,
    CIN                      VARCHAR2(20),
    NOM                      VARCHAR2(80)  NOT NULL,
    EMAIL                    VARCHAR2(120),
    SPECIALITE               VARCHAR2(80),
    DISPONIBILITE            VARCHAR2(20)  DEFAULT 'DISPONIBLE',
    PHOTO                    BLOB,
    FACE_TEMPLATE            CLOB,
    FACE_TEMPLATE_UPDATED_AT DATE,
    FACE_ENABLED             NUMBER(1)     DEFAULT 1,
    RFID                     VARCHAR2(64),
    LAST_POINTAGE_DATE       DATE,
    SALAIRE                  NUMBER(12,3)  DEFAULT 1200,
    LAST_POINTAGE_TYPE       VARCHAR2(10),
    LAST_ENTRY_TIME          DATE,
    TOTAL_HOURS_TODAY        NUMBER(12,6)  DEFAULT 0,
    TOTAL_HOURS_MONTH        NUMBER(12,6)  DEFAULT 0,
    CONSTRAINT PK_EMPLOYE           PRIMARY KEY (ID_EMP),
    CONSTRAINT UQ_EMPLOYE_MATRICULE UNIQUE (MATRICULE),
    CONSTRAINT UQ_EMPLOYE_CIN       UNIQUE (CIN),
    CONSTRAINT UQ_EMPLOYE_EMAIL     UNIQUE (EMAIL),
    CONSTRAINT CK_EMPLOYE_SALAIRE   CHECK (SALAIRE >= 0),
    CONSTRAINT EMPLOYE_DISPONIBILITE_CK CHECK (DISPONIBILITE IN
        ('DISPONIBLE','INDISPONIBLE','EN_INTERVENTION','CONGE_NORMALE','CONGE_MALADIE','EN_CONGE','EN_CONGE_MALADIE'))
);

CREATE TABLE MATIERE_PREMIERE (
    ID_MP            NUMBER,
    REFERENCE        VARCHAR2(50)  NOT NULL,
    NOM              VARCHAR2(120) NOT NULL,
    QUANTITE         NUMBER        DEFAULT 0,
    SEUIL_CRITIQUE   NUMBER        DEFAULT 0,
    PRIX             NUMBER(12,3)  DEFAULT 0,
    DATE_FABRICATION DATE,
    DATE_ACHAT       DATE,
    NUM_FOUR         NUMBER,
    NOM_FOUR         VARCHAR2(50),
    EMAIL_FOUR       VARCHAR2(150),
    CONSTRAINT PK_MATIERE_PREMIERE PRIMARY KEY (ID_MP),
    CONSTRAINT UQ_MP_REFERENCE     UNIQUE (REFERENCE),
    CONSTRAINT CK_MP_QUANTITE      CHECK (QUANTITE >= 0),
    CONSTRAINT CK_MP_SEUIL         CHECK (SEUIL_CRITIQUE >= 0),
    CONSTRAINT CK_MP_PRIX          CHECK (PRIX >= 0)
);

CREATE TABLE BAC_INTEL (
    ID_BAC             NUMBER,
    NUM_SERIE          VARCHAR2(60)  NOT NULL,
    MODELE             VARCHAR2(60)  NOT NULL,
    REMPLISSAGE        NUMBER        DEFAULT 0,
    LOCALISATION_STOCK VARCHAR2(150),
    ID_COMMANDE        NUMBER,
    PRIX               NUMBER(12,3),
    STOCK              NUMBER,
    CAPACITE_BATTERIE  NUMBER(8,2),
    CARACTERISTIQUES   VARCHAR2(500),
    IMAGE_PATH         VARCHAR2(500),
    NUM_UNITE          NUMBER(4,0)   DEFAULT 1 NOT NULL,
    STATUT_BAC         VARCHAR2(20)  DEFAULT 'EN_ATTENTE' NOT NULL,
    CONSTRAINT PK_BAC_INTEL       PRIMARY KEY (ID_BAC),
    CONSTRAINT UQ_BAC_SERIE_UNITE UNIQUE (NUM_SERIE, NUM_UNITE),
    CONSTRAINT CK_BAC_REMPLISSAGE CHECK (REMPLISSAGE BETWEEN 0 AND 100),
    CONSTRAINT CK_BAC_STATUT      CHECK (STATUT_BAC IN ('EN_ATTENTE','EN_SERVICE','A_VIDER','EN_PANNE'))
);
CREATE INDEX IDX_BAC_NUM_SERIE ON BAC_INTEL (NUM_SERIE);

CREATE TABLE COMMANDE (
    ID_COMMANDE    NUMBER,
    ID_CLIENT      NUMBER        NOT NULL,
    QTE            NUMBER        NOT NULL,
    PRIORITE       VARCHAR2(16)  DEFAULT 'NORMALE',
    STATUT         VARCHAR2(30)  DEFAULT 'EN_PREPARATION',
    DATE_COMMANDE  DATE          DEFAULT SYSDATE,
    DATE_LIVRAISON DATE,
    PRIX_TOTAL     NUMBER(12,3)  DEFAULT 0,
    ADRESSE        VARCHAR2(300),
    REFER          VARCHAR2(9),
    START_ADRESSE  VARCHAR2(100),
    PATH_HISTORY   VARCHAR2(4000),
    CONSTRAINT PK_COMMANDE     PRIMARY KEY (ID_COMMANDE),
    CONSTRAINT FK_CMD_CLIENT   FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    CONSTRAINT CK_CMD_QTE      CHECK (QTE > 0),
    CONSTRAINT CK_CMD_PRIX     CHECK (PRIX_TOTAL >= 0),
    CONSTRAINT CK_CMD_PRIORITE CHECK (PRIORITE IN ('FAIBLE','NORMALE','HAUTE','URGENTE')),
    CONSTRAINT CHK_STATUT      CHECK (STATUT IN ('EN_PREPARATION','LIVREE','LIVRAISON_EN_COURS','ANNULEE'))
);

CREATE TABLE COMMANDE_BAC (
    ID_COMMANDE   NUMBER        NOT NULL,
    ID_BAC        NUMBER        NOT NULL,
    QTE           NUMBER        NOT NULL,
    PRIX_UNITAIRE NUMBER(12,3)  DEFAULT 0 NOT NULL,
    CONSTRAINT PK_COMMANDE_BAC     PRIMARY KEY (ID_COMMANDE, ID_BAC),
    CONSTRAINT FK_COMMANDE_BAC_CMD FOREIGN KEY (ID_COMMANDE) REFERENCES COMMANDE(ID_COMMANDE) ON DELETE CASCADE,
    CONSTRAINT FK_COMMANDE_BAC_BAC FOREIGN KEY (ID_BAC)      REFERENCES BAC_INTEL(ID_BAC),
    CONSTRAINT CK_COMMANDE_BAC_QTE  CHECK (QTE > 0),
    CONSTRAINT CK_COMMANDE_BAC_PRIX CHECK (PRIX_UNITAIRE >= 0)
);
CREATE INDEX IDX_COMMANDE_BAC_BAC ON COMMANDE_BAC (ID_BAC);

CREATE TABLE INTERVENTION (
    ID_INTER    NUMBER,
    ID_BAC      NUMBER        NOT NULL,
    DATE_INTER  DATE          DEFAULT SYSDATE,
    REFERENCE   VARCHAR2(60),
    DUREE       NUMBER(6,2)   DEFAULT 0,
    COUT        NUMBER(12,3)  DEFAULT 0,
    STATUT      VARCHAR2(20)  DEFAULT 'EN_COURS',
    TYPE        VARCHAR2(60),
    PRIORITE    VARCHAR2(15)  DEFAULT 'NORMALE',
    TECHNICIEN  VARCHAR2(40),
    DESCRIPT    VARCHAR2(255),
    ADRESSE     VARCHAR2(255),
    PHOTO_AVANT VARCHAR2(1000),
    PHOTO_APRES VARCHAR2(1000),
    MAIN_OEUVRE NUMBER(12,3),
    CONSTRAINT PK_INTERVENTION   PRIMARY KEY (ID_INTER),
    CONSTRAINT UQ_INTER_REFERENCE UNIQUE (REFERENCE),
    CONSTRAINT FK_INTER_BAC      FOREIGN KEY (ID_BAC) REFERENCES BAC_INTEL(ID_BAC),
    CONSTRAINT CK_INTER_STATUT   CHECK (STATUT IN ('EN_COURS','EN_ATTENTE','TERMINEE','ANNULEE')),
    CONSTRAINT CK_INTER_PRIORITE CHECK (PRIORITE IN ('FAIBLE','NORMALE','HAUTE','URGENTE')),
    CONSTRAINT CK_INTER_COUT     CHECK (COUT >= 0),
    CONSTRAINT CK_INTER_DUREE    CHECK (DUREE >= 0)
);

CREATE TABLE EFFECTUATION (
    ID_EMP   NUMBER NOT NULL,
    ID_INTER NUMBER NOT NULL,
    CONSTRAINT PK_EFFECTUATION    PRIMARY KEY (ID_EMP, ID_INTER),
    CONSTRAINT FK_EFFECTUATION_EMP   FOREIGN KEY (ID_EMP)   REFERENCES EMPLOYE(ID_EMP),
    CONSTRAINT FK_EFFECTUATION_INTER FOREIGN KEY (ID_INTER) REFERENCES INTERVENTION(ID_INTER)
);

CREATE TABLE FABRICATION (
    ID_MP       NUMBER NOT NULL,
    ID_BAC      NUMBER NOT NULL,
    QTE_UTILISE NUMBER NOT NULL,
    CONSTRAINT PK_FABRICATION     PRIMARY KEY (ID_MP, ID_BAC),
    CONSTRAINT FK_FABRICATION_MP  FOREIGN KEY (ID_MP)  REFERENCES MATIERE_PREMIERE(ID_MP),
    CONSTRAINT FK_FABRICATION_BAC FOREIGN KEY (ID_BAC) REFERENCES BAC_INTEL(ID_BAC)
);

CREATE TABLE ADMIN_NOTIFICATION (
    ID_NOTIF     NUMBER,
    TARGET_EMAIL VARCHAR2(255) NOT NULL,
    TITLE        VARCHAR2(255),
    BODY         VARCHAR2(2000),
    REF_TYPE     VARCHAR2(64),
    REF_ID       NUMBER,
    IS_READ      NUMBER(1)     DEFAULT 0,
    CREATED_AT   DATE          DEFAULT SYSDATE,
    CONSTRAINT PK_ADMIN_NOTIFICATION PRIMARY KEY (ID_NOTIF)
);

-- ============================================================================
--  TRIGGERS d'auto-incrément (ne s'activent que si l'ID n'est pas fourni)
-- ============================================================================

CREATE OR REPLACE TRIGGER CLIENT_BI
BEFORE INSERT ON CLIENT FOR EACH ROW WHEN (NEW.ID_CLIENT IS NULL)
BEGIN SELECT CLIENT_SEQ.NEXTVAL INTO :NEW.ID_CLIENT FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER EMPLOYE_BI
BEFORE INSERT ON EMPLOYE FOR EACH ROW WHEN (NEW.ID_EMP IS NULL)
BEGIN SELECT EMPLOYE_SEQ.NEXTVAL INTO :NEW.ID_EMP FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER MATIERE_PREMIERE_BI
BEFORE INSERT ON MATIERE_PREMIERE FOR EACH ROW WHEN (NEW.ID_MP IS NULL)
BEGIN SELECT MATIERE_PREMIERE_SEQ.NEXTVAL INTO :NEW.ID_MP FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER BAC_INTEL_BI
BEFORE INSERT ON BAC_INTEL FOR EACH ROW WHEN (NEW.ID_BAC IS NULL)
BEGIN SELECT BAC_INTEL_SEQ.NEXTVAL INTO :NEW.ID_BAC FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER COMMANDE_BI
BEFORE INSERT ON COMMANDE FOR EACH ROW WHEN (NEW.ID_COMMANDE IS NULL)
BEGIN SELECT COMMANDE_SEQ.NEXTVAL INTO :NEW.ID_COMMANDE FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER TRG_CMD_REF
BEFORE INSERT ON COMMANDE FOR EACH ROW WHEN (NEW.REFER IS NULL)
BEGIN :NEW.REFER := 'CMD-' || LPAD(SEQ_CMD_REF.NEXTVAL, 3, '0'); END;
/

CREATE OR REPLACE TRIGGER INTERVENTION_BI
BEFORE INSERT ON INTERVENTION FOR EACH ROW WHEN (NEW.ID_INTER IS NULL)
BEGIN SELECT INTERVENTION_SEQ.NEXTVAL INTO :NEW.ID_INTER FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER ADMIN_NOTIFICATION_BI
BEFORE INSERT ON ADMIN_NOTIFICATION FOR EACH ROW WHEN (NEW.ID_NOTIF IS NULL)
BEGIN SELECT ADMIN_NOTIFICATION_SEQ.NEXTVAL INTO :NEW.ID_NOTIF FROM DUAL; END;
/

COMMIT;
